### ISSUE TITLE
all picks is not counting total correct if user is missing once game

### ISSUE THREAD

**Issue by axosoft-arasha** [suceava/Foosball#44]
I entered the master picks and noticed the total in () was blank for dan because he was missing a couple of games.

**Comment by axosoft-arasha** [comment]
this is also the same for standings.

**Comment by suceava** [comment]
I can't repro this, it's calculating fine for me even when I have a missing pick .. also it should not have shown just (), that's kindda weird ... I wonder if there was an error client-side ... anyways this got changed a bit, try it again after I push tonight
