### ISSUE TITLE
I can't clear masterpicks picks after testing the pages? 

### ISSUE THREAD

**Issue by axosoft-arasha** [suceava/Foosball#48]

**Comment by suceava** [comment]
I did not plan on adding ability to clear/delete picks .. is this something you'd need on a regular basis? ... If you just need to do it once right now while testing, just run this query to delete all master picks other than week 1
delete  from Picks where ScheduleId in (select Id from Schedules where Week > 1) and UserId='00000000-0000-0000-0000-000000000000'

master pick user id will always be set to 00000000-0000-0000-0000-000000000000

**Comment by axosoft-arasha** [comment]
I already ran the query today several times today but then realized I won't be needing to unless I accidental click on a team :) I ran it without the where clause. 

Sent via iPhone
Arash Amini

**Comment by axosoft-arasha** [comment]
I meant the ScheduledId part not userid

Sent via iPhone
Arash Amini
