### ISSUE TITLE
Lock message when all schedules have been locked

### ISSUE THREAD

**Issue by axosoft-arasha** [suceava/Foosball#50]

**Comment by axosoft-arasha** [comment]
It goes away when I do a masterpick not lock schedule.

**Comment by axosoft-arasha** [comment]
I removed the masterpicks and noticed all the week 1 games are locked but the message shows up.

**Comment by axosoft-arasha** [comment]
![screen shot 2015-08-22 at 3 32 09 pm](https://cloud.githubusercontent.com/assets/1110691/9426193/a9690992-48e5-11e5-84d5-e82b2d5f09e4.png)

**Comment by suceava** [comment]
Ah, yeah, I had the logic wrong, looking at any master picks (tho in theory you shouldn't have master picks without having locked the schedule) ... anyway, fixed properly
