### ISSUE TITLE
Update the points placeholder to font-size: 10px;

### ISSUE THREAD

**Issue by axosoft-arasha** [suceava/Foosball#93]
Its cut off right now and changing to 10 fixes the issue.

**Comment by suceava** [comment]
The `placeholder` seems a bit tricky to change.  While according to the docs this is supported in CSS - https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#Browser_compatibility - IE Edge & 10+ supposedly support changing it, they do not support changing the font specifically :(
